### ISSUE TITLE
Does this package support multilevel modeling?

### ISSUE THREAD

**Issue by ReichYang** [aalfons/robmed#33]
Hi, I'm looking to do a mediation analysis with clustered data so I probably need to have mixed-effects model. Can we achieve this with this package?

**Comment by aalfons** [comment]
Thanks for the interest in the package. 

Mixed-effects models are currently not implemented in package `robmed`. Robust estimators for mixed-effects models do exist, but I don't think that the fast-and-robust bootstrap methodology has been developed for them. So it will require some methodological development to realize this feature.

I'll put this on my list, but I cannot make any promises or provide a time line at this point. There are other features that have higher priority.

**Comment by aalfons** [comment]
I'm closing this now because there is also issue https://github.com/aalfons/robmed/issues/35 regarding this feature.
