### ISSUE TITLE
test_mediation 

### ISSUE THREAD

**Issue by akgraham89** [aalfons/robmed#37]
I've checked all of my variables, my entire line of code for the model, and more, and I still get this message (the same code worked a few weeks ago):

Error in `[.data.frame`(data, , m, drop = FALSE) : 
  undefined columns selected

**Comment by aalfons** [comment]
Without a reproducible example, I can only speculate what is going wrong. The error message means that the specified mediator variables are not found in the specified data set. Did you make sure that the supplied variable names are exactly as they are in the data set? In particular, check lower case vs upper case letters, any spaces, and so on.

Please let me know if that resolves the issue. Alternatively, you can of course send me a reproducible example.

**Comment by akgraham89** [comment]
As it turns out, one of my variables was recoded into a matrix, not a vector. Once addressed, all is working. Thank you again for your quick response!
